rules:
  class-name-format: 0
  clean-import-paths: 0
  hex-notation:
    - 1
    -
      style: uppercase
  leading-zero: 0
  nesting-depth: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-ids: 0
  no-url-domains: 0
  no-url-protocols: 0
  quotes:
    - 1
    -
      style: double
